#!groovy

def sharedLib = new SharedLib()

def commitGradlePluginReleaseVersion() {
    sh "(cd lightning-gradle-plugin; sed -i -e \"/lightningGradlePluginVersion=/ s/=.*/=${RELEASE_VERSION}/\" gradle.properties)"
    sh "(cd lightning-gradle-plugin; cat gradle.properties)"
    sh "git add -A; git commit -m 'Release version bump'"
}

def commitGradlePluginSnapshotVersion() {
    sh "(cd lightning-gradle-plugin; sed -i -e \"/lightningGradlePluginVersion=/ s/=.*/=${POST_RELEASE_SNAPSHOT_VERSION}/\" gradle.properties)"
    sh "(cd lightning-gradle-plugin; cat gradle.properties)"
    sh "git add -A; git commit -m 'Post-release version bump'"
}

def testGradlePlugin() {
    try {
        sh "(cd lightning-gradle-plugin; ./gradlew clean check -i)"
    } finally {
        junit 'lightning-gradle-plugin/build/test-results/*.xml'
    }
}

def tagGradlePluginRelease() {
    sh "git tag gradle-plugin-${RELEASE_VERSION}"
}

def releaseGradlePlugin() {
    // Maven Central
    sh '(cd lightning-gradle-plugin; ./gradlew clean uploadArchives -i)'
    // Gradle Plugin Portal
    sh "(cd lightning-gradle-plugin; ./gradlew clean publishPlugins -i)"

}



node {
    stage('Prepare') {
        sharedLib.cleanupWorkspaceAndCloneRepo()
        sharedLib.purge()
    }
    stage('Set release version number') {
        if ("${TEST_ONLY}" == "false") {
            commitGradlePluginReleaseVersion()
        }
    }
    stage('Run checks') {
        testGradlePlugin()
    }
    stage('Tag release') {
        if ("${TEST_ONLY}" == "false") {
            tagGradlePluginRelease()
        }
    }
    stage('Release') {
        if ("${TEST_ONLY}" == "false" && "${DRY_RUN}" == "false") {
            releaseGradlePlugin()
        }
    }
    stage('Set snapshot version number') {
        if ("${TEST_ONLY}" == "false") {
            commitGradlePluginSnapshotVersion()
        }
    }
    stage('Push release to origin/master') {
        if ("${TEST_ONLY}" == "false" && "${DRY_RUN}" == "false") {
            sharedLib.push()
        }
    }
}