#!groovy

library "SharedLib@${env.BRANCH_NAME}"

properties([
        [$class: 'BuildDiscarderProperty', strategy: [$class: 'LogRotator', artifactDaysToKeepStr: '', artifactNumToKeepStr: '', daysToKeepStr: '', numToKeepStr: '10']],
        parameters([
                string(name: 'RELEASE_VERSION', defaultValue: '9.0.0', description: ''),
                string(name: 'POST_RELEASE_SNAPSHOT_VERSION', defaultValue: '9.0.1-SNAPSHOT', description: ''),
                string(name: 'BUILD_CORE', defaultValue: 'false', description: ''),
                string(name: 'TEST_ONLY', defaultValue: 'true', description: ''),
                string(name: 'DRY_RUN', defaultValue: 'true', description: '')
        ])
])

def runIntegrationTests() {
    try {
        withEnv(["PATH+MAVEN=${tool 'M3'}/bin"]) {
            sh "mvn -pl jmeter-lightning-maven-plugin clean verify"
        }
    } finally {
        jacoco execPattern: '**/jmeter-lightning-maven-plugin/target/jacoco.exec', classPattern: '**/jmeter-lightning-maven-plugin/target/classes', sourcePattern: '**/jmeter-lightning-maven-plugin/src/main/java'
    }
}

def commitMavenPluginReleaseVersion() {
    withEnv(["PATH+MAVEN=${tool 'M3'}/bin"]) {
        dir('jmeter-lightning-maven-plugin') {
            sh "mvn versions:set -DnewVersion=${params.RELEASE_VERSION}"
        }
        sh "git add -A; git commit -m 'JMeter Lightning Maven Plugin release version bump'"
    }
}

def commitMavenPluginSnapshotVersion() {
    withEnv(["PATH+MAVEN=${tool 'M3'}/bin"]) {
        dir('jmeter-lightning-maven-plugin') {
            sh "mvn versions:set -DnewVersion=${params.POST_RELEASE_SNAPSHOT_VERSION}"
        }
        sh "git add -A; git commit -m 'JMeter Lightning Maven Plugin post-release version bump'"
    }
}

def tagMavenPluginRelease() {
    sh "git tag maven-plugin-${params.RELEASE_VERSION}"
}

def releaseMavenPlugin() {
    withEnv(["PATH+MAVEN=${tool 'M3'}/bin"]) {
        withCredentials([string(credentialsId: 'gpg-passphrase', variable: 'GPGPP')]) {
            sh "mvn -pl jmeter-lightning-maven-plugin clean deploy -P release -Dgpg.passphrase=${GPGPP}"
        }
    }
}

disableConcurrentBuilds()

timestamps {
    lock('lightning-pipeline') {
        node('linux') {
            stage('Prepare') {
                cleanupWorkspaceAndCloneRepo()
                sh "git checkout ${env.BRANCH_NAME}"
                purge()
            }
            stage('Build lightning-core') {
                if ("${params.BUILD_CORE}" == "true") {
                    buildCore()
                }
            }
            stage('Set release version number') {
                if ("${params.TEST_ONLY}" == "false") {
                    commitMavenPluginReleaseVersion()
                }
            }
            stage('Integration test') {
                runIntegrationTests()
            }
            stage('Tag release') {
                if ("${params.TEST_ONLY}" == "false") {
                    tagMavenPluginRelease()
                }
            }
            stage('Release') {
                if ("${params.TEST_ONLY}" == "false" && "${params.DRY_RUN}" == "false" && env.BRANCH_NAME == "master") {
                    releaseMavenPlugin()
                }
            }
            stage('Set snapshot version number') {
                if ("${params.TEST_ONLY}" == "false") {
                    commitMavenPluginSnapshotVersion()
                }
            }
            stage('Push release to origin/master') {
                if ("${params.TEST_ONLY}" == "false" && "${params.DRY_RUN}" == "false" && env.BRANCH_NAME == "master") {
                    push()
                }
            }
        }
    }
}