#!groovy

library "SharedLib@${env.BRANCH_NAME}"

pipeline {
    agent {
        label 'linux'
    }
    parameters {
        string(name: 'RELEASE_VERSION', defaultValue: '9.0.0', description: '')
        string(name: 'POST_RELEASE_SNAPSHOT_VERSION', defaultValue: '9.0.1-SNAPSHOT', description: '')
        string(name: 'BUILD_CORE', defaultValue: 'true', description: '')
        string(name: 'TEST_ONLY', defaultValue: 'true', description: '')
        string(name: 'DRY_RUN', defaultValue: 'true', description: '')
    }
    options {
        timestamps()
        skipDefaultCheckout()
        disableConcurrentBuilds()
        buildDiscarder(logRotator(numToKeepStr: '10'))
    }
    stages {
        stage('Prepare') {
            steps {
                cleanupWorkspaceAndCloneRepo()
                sh "git checkout ${env.BRANCH_NAME}"
                purge()
            }
        }
        stage('Build lightning-core') {
            when {
                expression {
                    "${params.BUILD_CORE}" == "true"
                }
            }
            steps {
                buildCore()
            }
        }
        stage('Set release version number') {
            when {
                expression {
                    "${params.TEST_ONLY}" == "false"
                }
            }
            steps {
                sh "./mvnw -pl lightning-standalone versions:set -DnewVersion=${params.RELEASE_VERSION}"
                sh "git add -A; git commit -m 'Lightning Standalone release version bump'"
            }
        }
        stage('Run unit tests, generate JAR file and run E2E tests') {
            steps {
                sh './mvnw -pl lightning-standalone clean compile assembly:single test'
            }
            post {
                always {
                    junit 'lightning-standalone/target/surefire-reports/junitreports/*.xml'
                    jacoco execPattern: '**/lightning-standalone/target/jacoco.exec', classPattern: '**/lightning-standalone/target/classes', sourcePattern: '**/lightning-standalone/src/main/java'
                }
            }
        }
        stage('Tag release') {
            when {
                expression {
                    "${params.TEST_ONLY}" == "false"
                }
            }
            steps {
                sh "git tag standalone-${params.RELEASE_VERSION}"
            }
        }
        stage('Archive JAR') {
            steps {
                archiveArtifacts artifacts: 'lightning-standalone/target/lightning-standalone-*.jar'
            }
        }
        stage('Set snapshot version number') {
            when {
                expression {
                    "${params.TEST_ONLY}" == "false"
                }
            }
            steps {
                sh "./mvnw -pl lightning-standalone versions:set -DnewVersion=${params.POST_RELEASE_SNAPSHOT_VERSION}"
                sh "git add -A; git commit -m 'Lightning Standalone post-release version bump'"
            }
        }
        stage('Push release to origin/master') {
            when {
                expression {
                    "${params.TEST_ONLY}" == "false" && "${params.DRY_RUN}" == "false" && "${env.BRANCH_NAME}" == "master"
                }
            }
            steps {
                push()
            }
        }
    }
}
