#!groovy

def sharedLib = new SharedLib()

node {
    def mvn
    stage('Prepare') {
        sharedLib.prepare()
        sharedLib.purge()
    }
    stage('CORE - Test and install') {
        sharedLib.testAndInstallCore()
    }
    stage('STANDALONE - Generate JAR file') {
        sharedLib.buildStandaloneJar()
    }
    stage('STANDALONE - Help') {
        sharedLib.checkStandaloneJarHelpExitCodes()
    }
    stage('STANDALONE - Stubbed ITs') {
        sharedLib.runStandaloneJarStubbedITs()
    }
//     Disabled until we find out how to run nohup from Jenkins job on macOS
//    stage('STANDALONE - ITs (CSV)') {
//        sharedLib.runStandaloneCsvITs()
//    }
//    stage('STANDALONE - ITs (SDW)') {
//        sharedLib.runStandaloneSdwITs()
//    }
    stage('MAVEN-PLUGIN - Install') {
        sharedLib.installMavenPlugin()
    }
    stage('MAVEN-PLUGIN - Stubbed ITs') {
        sharedLib.runMavenPluginStubbedITs()
    }
    stage('MAVEN-PLUGIN - ITs') {
        sharedLib.runMavenPluginITs()
    }
}