#!groovy

def sharedLib = new SharedLib()

node {
    stage('Prepare') {
        sharedLib.prepare()
        sharedLib.purge()
    }
    stage('Create release branch') {
        sh "git checkout -b feature/release"
    }
    stage('Set release version number') {
        sh "(cd lightning-core; ${mvn} versions:set -DnewVersion=${CORE_RELEASE_VERSION})"
        sh "(cd lightning-standalone; ${mvn} versions:set -DnewVersion=${STANDALONE_RELEASE_VERSION})"
        sh "(cd jmeter-lightning-maven-plugin; ${mvn} versions:set -DnewVersion=${PLUGIN_RELEASE_VERSION})"
        sh "git add -A; git commit -m 'Release version bump'"
    }
    stage('CORE - Test and install') {
        sharedLib.testAndInstallCore()
    }
    stage('CORE - Tag release') {
        sh "git tag core-${CORE_RELEASE_VERSION}"
    }
    stage('CORE - Release') {
        sh "${mvn} -pl lightning-core clean deploy -P release -Dgpg.passphrase=${GPG_PASSPHRASE}"
    }
    stage('STANDALONE - Generate JAR file') {
        sharedLib.buildStandaloneJar()
    }
    stage('STANDALONE - Help') {
        sharedLib.checkStandaloneJarHelpExitCodes()
    }
    stage('STANDALONE - Stubbed ITs') {
        sharedLib.runStandaloneJarStubbedITs()
    }
    stage('STANDALONE - Tag release') {
        sh "git tag standalone-${STANDALONE_RELEASE_VERSION}"
    }
    stage('STANDALONE - Archive JAR') {
        archiveArtifacts artifacts: 'lightning-standalone/target/lightning-standalone-*.jar'
    }
    stage('MAVEN-PLUGIN - Install') {
        sharedLib.installMavenPlugin()
    }
    stage('MAVEN-PLUGIN - Stubbed ITs') {
        sharedLib.runMavenPluginStubbedITs()
    }
    stage('MAVEN-PLUGIN - ITs') {
        sharedLib.runMavenPluginITs()
    }
    stage('MAVEN-PLUGIN - Tag release') {
        sharedLib.runMavenPluginITs()
    }
    stage('MAVEN-PLUGIN - Release') {
        sh "${mvn} -pl jmeter-lightning-maven-plugin clean deploy -P release -Dgpg.passphrase=${GPG_PASSPHRASE}"
    }
    stage('Set snapshot version number') {
        sh "(cd lightning-core; ${mvn} versions:set -DnewVersion=${CORE_POST_RELEASE_SNAPSHOT_VERSION})"
        sh "(cd lightning-standalone; ${mvn} versions:set -DnewVersion=${STANDALONE_POST_RELEASE_SNAPSHOT_VERSION})"
        sh "(cd jmeter-lightning-maven-plugin; ${mvn} versions:set -DnewVersion=${PLUGIN_POST_RELEASE_SNAPSHOT_VERSION})"
        sh "git add -A; git commit -m 'Post-release version bump'"
    }
    stage('CORE - Test and install - snapshot') {
        sharedLib.testAndInstallCore()
    }
    stage('STANDALONE - Generate JAR file - snapshot') {
        sharedLib.buildStandaloneJar()
    }
    stage('STANDALONE - Help - snapshot') {
        sharedLib.checkStandaloneJarHelpExitCodes()
    }
    stage('STANDALONE - Stubbed ITs - snapshot') {
        sharedLib.runStandaloneJarStubbedITs()
    }
    stage('MAVEN-PLUGIN - Install - snapshot') {
        sharedLib.installMavenPlugin()
    }
    stage('MAVEN-PLUGIN - Stubbed ITs - snapshot') {
        sharedLib.runMavenPluginStubbedITs()
    }
    stage('MAVEN-PLUGIN - ITs - snapshot') {
        sharedLib.runMavenPluginITs()
    }
    stage('Push release to origin/master') {
        sshagent(["${GIT_CREDENTIALS_ID}"]) {
            sh "git push --set-upstream origin master; git push --tags"
        }
    }
}